### ISSUE TITLE
Socket usages

### ISSUE THREAD

**Issue by chsivateja** [bitbns-official/bitbnspy#11]
Can you provide example on socket usage mentioned in README

**Comment by sanket-buyhatke** [comment]
Hi, @chsivateja currently web sockets are not supported on python sdk, it will be released very soon.

**Comment by its-mohnish** [comment]
Hi @chsivateja, We have just now released 0.2.1 version of bitbnspy over [here](https://pypi.org/project/bitbnspy/). It supports the use of web sockets. You can check on how to use them in our documentation.

**Comment by sanket-buyhatke** [comment]
hi, @chsivateja will be closing this issue as socket example has been updated in the documentation, feel free to reopen if you across any issue.
