### ISSUE TITLE
Enable getExecutedOrders function

### ISSUE THREAD

**Issue by soumya-sinclair** [bitbns-official/bitbnspy#14]
Currently ```getExecutedOrders``` is nto enabled and it returns error. Please enable it.

```
bitbnsObj.getExecutedOrders('EOS')
```

**Comment by sanket-buyhatke** [comment]
hi @soumya-sinclair, please use 
```python
symbol = 'EOSUSDT'    #symbol = 'EOS' for (EOS/INR market)
since_date = '2021-01-01T00:00:00Z'
page_no = 0
print(bitbnsObj.listExecutedOrders(symbol, since=since_date, pageNo=page_no))
```

response
```json
{
   "data":[
      {
         "type":"EOS Buy order executed",
         "typeI":29,
         "crypto":28,
         "amount":28,
         "rate":"3.3929",
         "date":"2021-01-06T18:53:25.000Z",
         "unit":"EOS",
         "factor":100,
         "fee":0.01,
         "delh_btc":0,
         "delh_inr":-0.96,
         "del_btc":28,
         "del_inr":0,
         "id":"2249410",
         "log_id":260236056
      }
   ],
   "status":1,
   "error":"None",
   "code":200
}
```

**Comment by soumya-sinclair** [comment]
@sanket-buyhatke What is the significance of pageno ? Should it be always kept 0 at my end ? 0 and 1 seems to give same results.

**Comment by soumya-sinclair** [comment]
@sanket-buyhatke Also can you please help me understand the fields ( or any document will also be good ). I am not seeing the volume of coin bought/sold.

![image](https://user-images.githubusercontent.com/60981021/103942971-46fe2f00-5157-11eb-83ec-c36d37b5a6b4.png)

**Comment by sanket-buyhatke** [comment]
@soumya-sinclair, 
1. significance of pageno is for pagination, if there is a large number of orders that need retrieval, suggested method would be to use pagination.
2. This particular function seems to be missing from the python documentation, thanks for the identification, will be updated soon.
as for the explanation of fields:
```
Explanation of fields:
type -> type of action
typeI -> action id
amount -> the amount deposited
date -> the time at which this event occurred
unit -> the symbol name of coin
factor -> the division factor
del_btc -> delta changes in normal wallet of coin
del_inr -> delta changes in normal inr wallet
delh_btc -> delta changes in hold wallet of coin
```
