### ISSUE TITLE
getTickerApi( 'EOS' ) API not returning status, error and code when successful

### ISSUE THREAD

**Issue by boral** [bitbns-official/bitbnspy#17]
`getTickerApi( 'EOS' )` returns different format in success and failure.

**Success**

![image](https://user-images.githubusercontent.com/12884971/105757886-9c6a7680-5f74-11eb-900f-9e3a352de188.png)

**Failure**

![image](https://user-images.githubusercontent.com/12884971/105758180-f703d280-5f74-11eb-830b-128d2bc88370.png)

Can you please add status, error and code in both cases. This will be helpful to handle errors using trycatch.

**Comment by sanket-buyhatke** [comment]
noted, will update soon.

thank you for your suggestion.

**Comment by its-mohnish** [comment]
Hi @boral, we have standardized the responses. You can update bitbnspy to 0.2.1 using pip for the same.

**Comment by sanket-buyhatke** [comment]
@boral , this has been updated, now the responses for all functions are standardised.
