### ISSUE TITLE
Unable to place sell order

### ISSUE THREAD

**Issue by boral** [bitbns-official/bitbnspy#18]
I have 5 units of GAS in wallet. However not able to place sell order. Please fix this.

![image](https://user-images.githubusercontent.com/12884971/105861905-3681fb80-6015-11eb-9326-31bf50bbb2ab.png)

**Comment by sanket-buyhatke** [comment]
hi @boral, you seem to be facing this issue as your order size is less than the required amount,
for INR net order should be greater than  ₹800 (via API)
for USDT net order should be greater than  $10 (via API)

please increase your volume and your order should be executed

**Comment by boral** [comment]
Thank you @sanket-buyhatke . Kindly document it for future reference. It will be very helpful.

**Comment by sanket-buyhatke** [comment]
noted, thanks for the suggestion.
