### ISSUE TITLE
Adding timeout for each API requests - otherwise api is hanging in case of non-reponse

### ISSUE THREAD

**Issue by boral** [bitbns-official/bitbnspy#20]
Please include a timeout of a predefined period say 10 seconds or 15 seconds or maybe user defined in each of the api calls. Otherwise if it takes too long time to get response, the code is just hanging and is not recovering from the api call.

To be specific, using this few lines of code mentioned here will fix for all the requests globally.

https://stackoverflow.com/a/61366068/8315634

**Comment by sanket-buyhatke** [comment]
thanks for the resources @boral , will try to implement it soon.

**Comment by sanket-buyhatke** [comment]
hi @boral, this has been updated, timeout has been set to 30 seconds.
