### ISSUE TITLE
withdrawHistory and depositHistory are giving status 204

### ISSUE THREAD

**Issue by sumanthtatipamula** [bitbns-official/bitbnspy#27]
getting status 204, when tried to get withdraw and deposit history for a coin
`{'data': [], 'status': 1, 'error': None, 'code': 204}`

**Comment by sanket-buyhatke** [comment]
hi, could you please specify for which pair you are facing this issue.

**Comment by its-mohnish** [comment]
Hi @sumanthtatipamula Yes, this is returned whenever you do not have any withdrawal or deposit history for a coin.
