### ISSUE TITLE
getTickerApi() giving error : AttributeError: 'str' object has no attribute 'pop'

### ISSUE THREAD

**Issue by boral** [bitbns-official/bitbnspy#28]
While running the following code, it is giving error : 

```
bitbnsObj = bitbns(key, secretKey)

bitbnsObj
Out[23]: <bitbnspy.bitbnspy.bitbns at 0x224b0b8b2b0>

bitbnsObj.getTickerApi( 'MATIC' )
Traceback (most recent call last):

  File "<ipython-input-24-17c6c2c9e69c>", line 1, in <module>
    bitbnsObj.getTickerApi( 'MATIC' )

  File "C:\anaconda\lib\site-packages\bitbnspy\bitbnspy.py", line 99, in getTickerApi
    req[key].pop('yes_price', None)

AttributeError: 'str' object has no attribute 'pop'

```

**Comment by sanket-buyhatke** [comment]
HI @boral , could you please describe your environment ?

**Comment by boral** [comment]
@sanket-buyhatke I am using Python 3.8.5

**Comment by CO17349** [comment]
While using the getTickerApi function, how to get the price of the token as per both INR and USD?

**Comment by its-mohnish** [comment]
Hi @boral, Are you still facing this issue? I have tried running this with python 3.8.5, and did not face this issue.

**Comment by boral** [comment]
No, it is working fine now.

**Comment by sanket-buyhatke** [comment]
great, will be closing this issue, feel free to re-open if you face the issue again.
