### ISSUE TITLE
getTickerApi for both the INR and USDT market

### ISSUE THREAD

**Issue by CO17349** [bitbns-official/bitbnspy#29]
Hi, how can I use getTickerApi function to get the price of the symbol in both INR and USDT markets? Or there's a different method to achieve this?

**Comment by sanket-buyhatke** [comment]
hi, @CO17349 

you can use `bitbnsObj.getTickerApi('')`, you'll be able to get price for all symbols (both INR and USDT market), you can extract required information for desired symbol from there.

**Comment by CO17349** [comment]
{'BTC': {'highest_buy_bid': 2865243.06, 'lowest_sell_bid': 2865269.92, 'last_traded_price': 2865269.92}

@ sanket-buyhatke, this is what bitbnsObj.getTickerApi('') has returned for BTC sir. It has no mention of INR or USD market. Any help please sir.

**Comment by sanket-buyhatke** [comment]
by default there are formats present
for INR market - there is suffix 
for USDT market - there is USDT suffix

eg.
```
'BTC': {'highest_buy_bid': 2865243.06, 'lowest_sell_bid': 2865269.92, 'last_traded_price': 2865269.92} -> INR market
'BTCUSDT':{'highest_buy_bid': 35605.55,'inr_price': 2800591.12,'last_traded_price': 35676.32,'lowest_sell_bid': 35712.9} -> USDT market 
```

**Comment by CO17349** [comment]
@sanket-buyhatke , thanks a ton once again. You've been a great support. Regards!
