### ISSUE TITLE
API allows to trade CPX 

### ISSUE THREAD

**Issue by its-mohnish** [bitbns-official/bitbnspy#39]
## Describe your environment

  * Operating system: windows
  * Python Version: 3.8.8

## Describe the problem:

CPX has been delisted from the marketplace. However, we can still get buy & sell order book, use getTickerApi, place stoploss orders and cancelOrders.

### Steps to reproduce:

  1. Load the bitbns obj in python
  2. Run API functions for CPX

### Observed Results:

  * I could get info. on CPX and place orders for it
  * It has been delisted 

#### Code Sample, a copy-pastable example

```python
API_KEY, SECRET_KEY = "####", "####"
bitbnsObj = bitbns(API_KEY, SECRET_KEY)
print(bitbnsObj.getTickerApi("CPX"))
print(bitbnsObj.buyStopLoss("CPX", 200, 0.35, 0.3))
print(bitbnsObj.cancelOrder("CPX", 47996))
```

#### logs, a copy-pastable example

```
{
 'CPX': 
   {'highest_buy_bid': 0.35, 
    'lowest_sell_bid': 0.36, 
    'last_traded_price': 0.36
  }
}
{
 'data': 'Successfully placed order for stop loss buy', 
 'status': 1, 
 'error': None, 
 'id': 147703, 
 'code': 200
}
{
 'data': 'Successfully cancelled the order', 
 'status': 1, 
 'error': None, 
 'code': 200
}
```

**Comment by atiprashant** [comment]
CPX is delisted now
