### ISSUE TITLE
Order status for stop loss orders

### ISSUE THREAD

**Issue by its-mohnish** [bitbns-official/bitbnspy#43]
## Describe the problem:

orderStatus function does not retrieve data for stop loss orders

### Steps to reproduce:

  1. Place a stop loss order
  2. Use the id to check for order status

### Observed Results:

  * Response with error field shows - "Nothing to show"
  * Response should show my open stop orders

#### Code Sample, a copy-pastable example

```python
bitbnsObj.buyStopLoss('USDT', 1, 80, 79)
bitbnsObj.orderStatus('USDT', 147718)
```

#### logs, a copy-pastable example

```
{
 'data': 'Successfully placed order for stop loss buy', 
 'status': 1, 
 'error': None, 
 'id': 147718, 
 'code': 200
}
{
 'data': [], 
 'status': 0, 
 'error': 'Nothing to show', 
 'code': 417
}
```

**Comment by atiprashant** [comment]
Only after a stop loss order gets executed, it will be visible in your open order or order status. Use listStopLoss order for order details of placed order
