### ISSUE TITLE
coins returning not supported error

### ISSUE THREAD

**Issue by its-mohnish** [bitbns-official/bitbnspy#44]
## Describe the problem:

Three tickers - WBTC, ZEBI and PHB have been returning coins not supported error.

### Steps to reproduce:

  1. Use any function on the three tickers mentioned above

### Observed Results:

  * Returned coin not supported error
  * Expected it to return a valid response

#### Code Sample, a copy-pastable example

```python
bitbnsObj.getBuyOrderBook('WBTC') #Could be any function except getTickerApi
```

#### logs, a copy-pastable example

```
{
 'data': '', 
 'status': 0, 
 'msg': 'coin name not supplied', 
 'code': 406
} 
```

**Comment by atiprashant** [comment]
This is sorted now
