### ISSUE TITLE
Placing orders - Irregular price problem 

### ISSUE THREAD

**Issue by its-mohnish** [bitbns-official/bitbnspy#46]
## Describe the problem:

Coins BCHSV, DENT, LET, CLOAK, BTT have been showing irregular price problem.

### Steps to reproduce:

  1. Place order for any of the coins mentioned above

### Observed Results:

  * Order not placed, produces irregular price problem
  * Order should have been placed 

#### Code Sample, a copy-pastable example

```python
#Actual market price during the posting of this issue was 12800
bitbnsObj.placeBuyOrder('BCHSV', 0.0043, 11500)
```

#### logs, a copy-pastable example

```
{
 'data': None, 
 'status': 0, 
 'error': 'Price seems Irregular from current market price. 31974.284532737227', 
 'code': 428
}
```

**Comment by atiprashant** [comment]
This is sorted
