### ISSUE TITLE
adding market order functionality

### ISSUE THREAD

**Issue by sanket-buyhatke** [bitbns-official/bitbnspy#48]
## Describe the enhancement

Implementation of market order via API trading, would help place orders immediately and ensures the user is able to enter/exit their position irrespective of market condition.

Currently this is achieved by  calling two functions (example for exiting BTC/USDT position):
`bitbnsObj.getSellOrderBook('BTCUSDT')`
`bitbnsObj.placeOrders({'symbol': 'BTCUSDT', 'side': 'SELL', 'quantity': 0.1, 'rate': 33000})`

this action could be achieved by just 1 action by user:
`bitbnsObj.placeOrders({'symbol': 'BTCUSDT', 'side': 'SELL', 'type':'MARKET', 'quantity': 0.1})` 
note: rate is not considered in this case.

**Comment by sukhwant280** [comment]
interesting.. on the website, only limit, stop and bracket are available. will try market via api. lets hope you resolve my installation issue no : 56 :-)

**Comment by sanket-buyhatke** [comment]
@sukhwant280 , the market order functionality is currently unavailable, hence the feature request (meaning you wont be able place market orders via API currently) 

will update in documentation, once it is available.

thank you for your interest.

**Comment by sukhwant280** [comment]
noted thanks

**Comment by sanket-buyhatke** [comment]
Hi @sukhwant280 , the market order functionality is live, pls refer to [market orders](https://github.com/bitbns-official/bitbnspy#place-market-order-via-cost)
