### ISSUE TITLE
Incorrect quantity for ETN - using listExecutedOrders

### ISSUE THREAD

**Issue by sanket-buyhatke** [bitbns-official/bitbnspy#49]
## Describe your environment

  * Operating system: mac os - 10.14.5
  * Python Version: 3.7.7

## Describe the problem:

symbol: ETN
quantity: 500

after placing an order for 500 ETN, while checking for executed orders the amount field the returned amount was showing 5000 ETN (10x more than the originally placed quantity), 
this issue seems to be only with this endpoint as on bitbns website the quantity was 500 ETN.

### Steps to reproduce:

  1. place order for ETN
  2. fetch executed order using listExecutedOrders function

### Observed Results:

  * What happened?
    - the quantity returned by endpoint is 5000 ETN
  * What did you expect to happen?
    - the quantity returned by endpoint is 500 ETN

#### Code Sample, a copy-pastable example

```python
# to place an order
side = 'BUY'
symbol = 'ETN'
min_amount = 380 
rate = 0.755
quantity = (min_amount / rate)
print(bitbnsObj.placeOrders({"symbol":symbol,"side":side,"quantity":quantity,"rate":rate}))

# to fetch executed order for ETN
symbol = 'ETN'
since_date = '2021-01-01T00:00:00Z'
page_no = 0
print(bitbnsObj.listExecutedOrders(symbol, since=since_date, pageNo=page_no))

```

#### logs, a copy-pastable example

```
// response for placing order
{'data': 'Successfully placed bid to purchase currency', 'status': 1, 'error': None, 'id': 549056, 'code': 200}

// response for fetch executed order for ETN
{'code': 200,
 'data': [{'amount': 3750,
           'crypto': 3750,
           'date': '2021-06-01T06:19:16.000Z',
           'del_btc': 3750,
           'del_inr': 2.63,
           'delh_btc': 0,
           'delh_inr': -283.84,
           'factor': 10,
           'fee': 0.71,
           'id': '547003',
           'rate': '0.755',
           'type': 'ETN Buy order executed',
           'typeI': 7,
           'unit': 'ETN'},
          {'amount': 1250,
           'crypto': 1250,
           'date': '2021-06-01T06:19:16.000Z',
           'del_btc': 1250,
           'del_inr': 0,
           'delh_btc': 0,
           'delh_inr': -94.62,
           'factor': 10,
           'fee': 0.24,
           'id': '547003',
           'rate': '0.755',
           'type': 'ETN Buy order executed',
           'typeI': 7,
           'unit': 'ETN'}],
 'error': None,
 'status': 1}
```

A snippet from the exchange to show the actual volume:
![image](https://user-images.githubusercontent.com/57214024/122713545-77f49b00-d283-11eb-8b6f-74853b389a13.png)

**Comment by atiprashant** [comment]
Please note the factor in the response. Dividing the amount by it will work for all coins.
