### ISSUE TITLE
Not supported coins for placeOrders

### ISSUE THREAD

**Issue by its-mohnish** [bitbns-official/bitbnspy#50]
## Describe the problem:

Coins BNB/USDT, BNSD/USDT, FET/USDT & FUN/USDT are returning not supported coins as response for placeOrders for order types - normal and stoploss

### Steps to reproduce:

  1. Run placeOrders function with just rate parameter and/or t_rate parameter set

### Observed Results:

  * Response code 406 - Coin not supported or name not supplied error
  * Should have placed order succesfully

#### Code Sample, a copy-pastable example

```python
bitbnsObj.placeOrders({'symbol': 'BNB_USDT', 'side': 'BUY', 'quantity': 0.01, 'rate': 290})
```

#### logs, a copy-pastable example

```
{
 'data': None, 
 'status': 0, 
 'error': 'Coin Type Not Valid or Not Supported Yet!!', 
 'code': 406
}
```

**Comment by atiprashant** [comment]
This is sorted now
