### ISSUE TITLE
No data is returned for a few pairs using - currentCoinBalance

### ISSUE THREAD

**Issue by sanket-buyhatke** [bitbns-official/bitbnspy#54]
## Describe your environment

  * Operating system: macos - 10.14.5
  * Python Version: 3.7.10

## Describe the problem:

`currentCoinBalance` returns no data for recently added pairs.

this issue is observed in USDC, BUSD, RUNE, SOL, SAND, MANA etc (while opening issue, there were most recently added)

### Steps to reproduce:

  1. fetch current coin balance via `currentCoinBalance` function.
  
### Observed Results:

  * What happened?
    - the data field returns empty value.
  * What did you expect to happen?
    - the data field to return 0 balance.

#### Code Sample, a copy-pastable example

```python
# Your code here
print(bitbnsObj.currentCoinBalance('BUSD'))

```

#### logs, a copy-pastable example

```
{'code': 200, 'data': {}, 'error': None, 'status': 1}
```

**Comment by sanket-buyhatke** [comment]
The work around this issue is, buying a small quantity of the asset, and then retrying the function, it seems to be working(even if the balance is reduced to 0 later)

```python
print(bitbnsObj.currentCoinBalance('BUSD'))
```

```
{
 'code': 200,
 'data': {'availableorderBUSD': 0, 'inorderBUSD': 29},
 'error': None,
 'status': 1
}
```

**Comment by atiprashant** [comment]
This is sorted
