### ISSUE TITLE
Bitbnspy Installation issue

### ISSUE THREAD

**Issue by sukhwant280** [bitbns-official/bitbnspy#56]
team,

did step 1:
Installation
sudo -H pip3 install python-socketio[client]
pip3 install bitbnspy

Step 2 ran this in spyder - python:

and got error of: "ModuleNotFoundError: No module named 'bitbnspy'"

please help how to resolve this

thanks
sukhwant

code used to run on spyder:

from bitbnspy import bitbns
key = 'yourKey'
secretKey = 'yourSecretKey'
bitbnsObj = bitbns(key, secretKey)
print(bitbnsObj.getSellOrderBook('XRPUSDT'))

**Comment by sukhwant280** [comment]
@sanket-buyhatke @atiprashant @tanmesh - please opine

**Comment by sanket-buyhatke** [comment]
@sukhwant280, thanks for open the issue, could you pls provide your python version ?
you can find it by running `python -V`,

also could you pls follow the template for reporting issues, so the next person facing similar issues would be able to resolve it quickly.

**Comment by sukhwant280** [comment]
Python version is 3.8.10 and operating system is win 10.

apologies will follow the template going forward, as a comer in this space.

**Comment by sanket-buyhatke** [comment]
no issues

can pls check if installation has been successful  and ping the response here?  
you can find it by `pip freeze | findstr 'bitbnspy'`

**Comment by sukhwant280** [comment]
![sc1](https://user-images.githubusercontent.com/86493449/123551150-389be200-d78e-11eb-83aa-ce85cf5adf39.jpg)
 attached screeshot

**Comment by sanket-buyhatke** [comment]
hi, @sukhwant280, looks like `bitbnspy` has been installed successfully, if you do this in the  windows `cmd`, it should work,
`python`
`from bitbnspy import bitbns`

mostly likely reason I can think of is, spyder uses a virtual environment, and hence you are unable to use bitbns module there, I would suggest installing `bitbnspy` package in your spyder environment.
if you are using [spyder without anaconda](https://miamioh.instructure.com/courses/38817/pages/downloading-and-installing-packages?module_item_id=429168) 
if you are using [spyder with anaconda](https://www.tutorialspoint.com/add-packages-to-anaconda-environment-in-python)

**Comment by sukhwant280** [comment]
Thanks Sanket. 
Solution - install bitbnspy on Conda environment. i did on Pip only.

its working. if any issues with apis, will follow the format and raise new tickets.

thanks for your help. we can close this item
