### ISSUE TITLE
BTC/INR pair giving wrong Qty via api

### ISSUE THREAD

**Issue by sukhwant280** [bitbns-official/bitbnspy#57]
## Describe your environment

  * Operating system: Windows 10
  * Python Version: 3 above via conda platform

## Describe the problem:

running this Api:
pd.json_normalize(bitbnsObj.getBuyOrderBook(BTC), "data", meta=["status", "error","code"])

### Observed Results:

  * What happened?
  Output is coming as below:
0
dict
2
{'rate': 2666145.61, 'btc': 7050}
1
dict
2
{'rate': 2663113.45, 'btc': 87190000}
2
dict
2
{'rate': 2663069.89, 'btc': 19216500}
3
dict
2
{'rate': 2662923.18, 'btc': 7543600}
4
dict
2
{'rate': 2662518.18, 'btc': 26679500}
5
dict
2
{'rate': 2662454.75, 'btc': 16096000}
6
dict
2
{'rate': 2662453.99, 'btc': 43969700}
7
dict
2
{'rate': 2662164.37, 'btc': 4170200}
8
dict
2
{'rate': 2662144.51, 'btc': 8369799}
9
dict
2
{'rate': 2662027.59, 'btc': 7842000}
10
dict
2
{'rate': 2661978.69, 'btc': 32316200}
11
dict
2
{'rate': 2652240.89, 'btc': 18641647}
12
dict
2
{'rate': 2650352.7, 'btc': 3764}
13
dict
2
{'rate': 2649811.09, 'btc': 186252}
14
dict
2
{'rate': 2642000, 'btc': 301846}
  * What did you expect to happen?
BTC Value - which is qty to be in range of 0.1289 onwards

please opine

**Comment by sanket-buyhatke** [comment]
hi @sukhwant280, the quantity here needs to refactored to 10^-8 decimals (currently it is displayed in sats).

e.g
```python
data = {'rate': 2663113.45, 'btc': 87190000}
vol = data['btc'] * (10 ** -8)
print(vol)
```
output:
```
0.8719
```

**Comment by sukhwant280** [comment]
should not this be already factored in the api.. as there are so many other coins and will be challenging to resolve for these specific coins?

Enhancement request can we take and if taking, please provide eta.

thanks
sukhwant

**Comment by sanket-buyhatke** [comment]
AFAIK, only btc

noted. (as changing it on the backend could disrupt the flow for those who have implemented the refactoring, it will take a while to roll out the change)

would suggest implementing client side change for now.

**Comment by sukhwant280** [comment]
noted. just to confirm, BTC is only coin to be refactored?

please close the ticket after response

**Comment by sanket-buyhatke** [comment]
yes
