### ISSUE TITLE
How to execute a coin in USDT market via api

### ISSUE THREAD

**Issue by sukhwant280** [bitbns-official/bitbnspy#58]
## Describe your environment

* Operating system: Windows 10
* Python Version: 3.8.3

## Your question
 how to execute a coin in USDT market via api

```python
import pandas as pd
import datetime as dt
import time
import numpy as np
import http.client
import json
from bitbnspy import bitbns
from BitbnsTradeSuggestions import tradexecute

key = ''
secretKey = ''
bitbnsObj = bitbns(key, secretKey)


tdticker1 = 'XRP_USDT'
tdtickerqty1 = 146.43
tdtickerprice1 = 0.6829

tdticker2 = 'XRP'
tdtickerqty2 = 146.43
tdtickerprice2 = 51

bitbnsObj.placeBuyOrder(tdticker1, tdtickerqty1, tdtickerprice1) 
time.sleep(5)
bitbnsObj.placeSellOrder(tdticker2, tdtickerqty2, tdtickerprice2)

```
Pleas note: Trade does not get executed, even if USDT of $100 is in the wallet. Rates mentioned in the Ask to buy and bid to sell are present in the order book

Please opine

**Comment by sukhwant280** [comment]
OR i should use the fromat of Bracket execution order to place a simple order?

**Comment by sanket-buyhatke** [comment]
`placeBuyOrder` only supports INR pairs which is version 1
please use `placeOrders` which supports both INR and USDT pairs, which is version 2.

yes, you can use the bracket order format, all fields are not necessary, you use only what is required for a simple order.
e.g.
```python
#to place a simple buy order for USDT pairs
bitbnsObj.placeOrders({'symbol': 'XRP_USDT', 'side': 'BUY', 'quantity': 146.43, 'rate': 0.6829}))
```

**Comment by sukhwant280** [comment]
thanks its working now
