### ISSUE TITLE
bitbnsObj.currentCoinBalance('ICP') not fetching standard response

### ISSUE THREAD

**Issue by boral** [bitbns-official/bitbnspy#60]
I am trying to fetch currentCoinBalance for ICP however I am facing the following issue

![image](https://user-images.githubusercontent.com/12884971/124808616-c5a81d80-df7c-11eb-94f8-9abebd7b3797.png)

**Code**

```
bitbnsObj = bitbns(key, secretKey)
bitbnsObj.currentCoinBalance(coin)
```

**Comment by sanket-buyhatke** [comment]
@boral , thanks for opening the issue, from the next time could you pls provide your python version ? this would help us to reproduce the issue on our end.
you can find it by running `python -V`,

also could you pls follow the template for reporting issues, so the next person facing similar issues would be able to resolve it quickly.

about the issue raised, this is a known bug, pls refer to the work around -> https://github.com/bitbns-official/bitbnspy/issues/54#issue-927921495.
feel free to continue the thread if you still face the issue.

**Comment by atiprashant** [comment]
This has been sorted. Please verify and close it @sanket-buyhatke
