### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by vijaySai-22** [bitbns-official/bitbnspy#69]
AttributeError: type object 'bitbns' has no attribute 'publicEndpoints'

## Describe your environment

* Operating system: ubuntu
* Python Version: 3.8.8 (`python -V`)

## Your question
AttributeError: type object 'bitbns' has no attribute 'publicEndpoints'

```python
from bitbnspy import bitbns
bitbnsObj = bitbns.publicEndpoints()
print(bitbnsObj.fetchTickers())

```

**Comment by sanket-buyhatke** [comment]
Hi @vijaySai-22 , this is sorted now, pls check

**Comment by vijaySai-22** [comment]
> Hi @vijaySai-22 , this is sorted now, pls check

Not working still shows same..
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 2, in <module>
AttributeError: type object 'bitbns' has no attribute 'publicEndPoints'

**Comment by sanket-buyhatke** [comment]
would suggest updating your bitbns python package, you can do that using
`pip3 install bitbnspy --upgrade`

**Comment by sanket-buyhatke** [comment]
hope this is resolved, would be closing the issue,  feel free to reopen it if you are facing the issue again

**Comment by vijaySai-22** [comment]
> hope this is resolved, would be closing the issue, feel free to reopen it if you are facing the issue again

it's working fine
thank you

**Comment by rituranjna** [comment]
bitbnsObj = bitbns.publicEndpoints()
AttributeError: type object 'bitbns' has no attribute 'publicEndpoints'

**Comment by sanket-buyhatke** [comment]
@rituranjna 

could you pls try again after upgrading your bitbns version, you can upgrade it using 
```
pip3 install bitbnspy --upgrade
```
