### ISSUE TITLE
Not able to get USDT withdrawal history with api

### ISSUE THREAD

**Issue by wildered** [bitbns-official/bitbnspy#71]
It is not possible to get the withdrawal history for USDT

`>BITBNS_API.withdrawHistory("USDT", page=0)`
`Out[1]: {'data': [], 'status': 1, 'error': None, 'code': 204}`

There should be data, and code = 200
Does this require a separate code per withdrawal network?

Thank you

**Comment by sanket-buyhatke** [comment]
Hi, @wildered 

`'data': []` would be case, if there has been no withdrawal done yet,
 
 could you pls try again, after a withdrawal ?
if you are still facing an issue, you can dm on telegram @zero_d_0

since it seems to be working on my end.

```
{'code': 200,
          {'amount': 10.1,
           'canSendMail': 0,
           'cancelable': -1,
           'expTime': 'USDT withdraw done',
           'fee': 10,
           'hash': '0x89c237167d8d7f3fbb99e2ad31ebe2377f3ae0bc8c6ac4e1ef3650257f657084',
           'refer': 28441,
           'status': '-1',
           'timestamp': '2021-09-08T16:44:27.000Z',
           'to': '0xaEF07V82E2a55c63eaC4F1b7a0e60101e83bGd4b',
           'type': 0,
           'unit': 'USDT'}],
 'error': None,
 'status': 1}
```

**Comment by sanket-buyhatke** [comment]
hi, @wildered, would be closing this, feel free to reopen this incase you face the same issue again.
