### ISSUE TITLE
Module bitbns not present

### ISSUE THREAD

**Issue by bigbomaks** [bitbns-official/bitbnspy#8]
>>> import bitbnspy
>>> help("bitbnspy")
Help on package bitbnspy:

NAME
    bitbnspy

PACKAGE CONTENTS
    bitbns
    bitbnspy
    main

FILE
    c:\users\singha2\appdata\local\programs\python\python36\lib\site-packages\bitbnspy\__init__.py

>>> from bitbns import bitbnsApi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'bitbns'

**Comment by tanmesh** [comment]
try "from bitbnspy import bitbns"

**Comment by bigbomaks** [comment]
Working fine now 
Thanks for quick resolution
