### ISSUE TITLE
swap order is not working 

### ISSUE THREAD

**Issue by durveshodi** [bitbns-official/bitbnspy#82]
HTTPSConnectionPool(host='api.bitbns.com', port=443): Read timed out. (read timeout=30)
{'data': None, 'status': 0, 'error': 'Invalid Non-JSON response - swapLimitINR'}

i got above error when i place swap order
this command i used 
bitbnsObj.swapLimitINR({'coin': 'BTC', 'quantity':0.000005, 'rate': 3358000, 'type': 0})

**Comment by its-mohnish** [comment]
Hi,
I think this is an issue with your network connection. Can you please check that once again

**Comment by sanket-buyhatke** [comment]
closing this issue, please feel free to reopen if you are facing the issue again
