### ISSUE TITLE
API trading issue

### ISSUE THREAD

**Issue by wgood1866** [bitbns-official/bitbnspy#83]
## Describe your environment

  * Operating system: ____
  * Python Version: _____ (`python -V`)

## Describe the problem:
unable to place order using bitbns API on bituniverse 
it shows the following error
Error_in_grpc_call
*Explain the problem you have encountered*

### Steps to reproduce:

  1. _____
  2. _____
  3. _____

### Observed Results:

  * What happened?unable to place order using bitbns API on bituniverse 
it shows the following error
Error_in_grpc_call
  * What did you expect to happen?unable to place order using bitbns API on bituniverse 
it shows the following error
Error_in_grpc_call

#### Code Sample, a copy-pastable example

```python
# Your code here

```

#### logs, a copy-pastable example

```
// paste your log here
```

**Comment by sanket-buyhatke** [comment]
It should be sorted now, could you pls check again

**Comment by sanket-buyhatke** [comment]
closing this issue, pls reopen if you face it again
