### ISSUE TITLE
Placing orders - Irregular price problem

### ISSUE THREAD

**Issue by mitesh-mutha** [bitbns-official/bitbnspy#88]
Coin LRC have been showing irregular price problem.

## Steps to reproduce:
Place order for the coin mentioned above

## Observed Results:

- Order not placed, produces irregular price problem
- Order should have been placed

### logs, a copy-pastable example
{
 'data': None, 
 'status': 0, 
 'error': 'Price seems Irregular from current market price. 18.180279665397926', 
 'code': 428
}

**Comment by sanket-buyhatke** [comment]
could you pls share more details on how to reproduce this issue ?
- which coin was the issue observed for ?
- what was the payload ?

**Comment by mitesh-mutha** [comment]
The problem resolved itself. Will close this.

**Comment by sanket-buyhatke** [comment]
noted
